In [1]:
#Here I have imported numpy so that I can treat the sudoku as a two dimensional array and not as a list
import numpy as np
#Here I have put a solved sudoku in so that we can use the checker on it.
sudoku = np.array([[5,3,4,6,7,8,9,1,2],[6,7,2,1,9,5,3,4,8],[1,9,8,3,4,2,5,6,7],[8,5,9,7,6,1,4,2,3],[4,2,6,8,5,3,7,9,1],[7,1,3,9,2,4,8,5,6],[9,6,1,5,3,7,2,8,4],[2,8,7,4,1,9,6,3,5],[3,5,4,2,8,6,1,7,9]])
print(sudoku)
score = 0
# print(sudoku[0:3,0:3]) This prints the first 3x3 grid
# print(sudoku[0]) This prints the first row

#This checks all the rows are correct.
for i in range(0,9):
    if 1 and 2 and 3 and 4 and 5 and 6 and 7 and 8 and 9 in sudoku[i]:
        score+=1
        print("Score:",score)
    else:
        print("Error in row", i)

#This checks all the collumns are correct.
for i in range(0,9):
    if 1 and 2 and 3 and 4 and 5 and 6 and 7 and 8 and 9 in sudoku[:,i]:
        score+=1
        print("Score:", score)
    else:
        print("Error in collumn:", i)
        
#This checks that the 3x3 grids are correct
for k in range(3,10,3):
    m = k-3
    for i in range(3,10,3): 
        j = i-3
        if 1 and 2 and 3 and 4 and 5 and 6 and 7 and 8 and 9 in (sudoku[j:i,m:k]):
            score+=1
            print("Score:", score)
        else:
            print("Error in grid:", sudoku[j:i,m:k])

if score==27:
    print("This is a correct solution for the sudoku.")
else:
    print("This solution is incorrect.")

[[5 3 4 6 7 8 9 1 2]
 [6 7 2 1 9 5 3 4 8]
 [1 9 8 3 4 2 5 6 7]
 [8 5 9 7 6 1 4 2 3]
 [4 2 6 8 5 3 7 9 1]
 [7 1 3 9 2 4 8 5 6]
 [9 6 1 5 3 7 2 8 4]
 [2 8 7 4 1 9 6 3 5]
 [3 5 4 2 8 6 1 7 9]]
Score: 1
Score: 2
Score: 3
Score: 4
Score: 5
Score: 6
Score: 7
Score: 8
Score: 9
Score: 10
Score: 11
Score: 12
Score: 13
Score: 14
Score: 15
Score: 16
Score: 17
Score: 18
Score: 19
Score: 20
Score: 21
Score: 22
Score: 23
Score: 24
Score: 25
Score: 26
Score: 27
This is a correct solution for the sudoku.
